spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cems_service
    username: postgres
    password: {ciper}d3472f6b336ac7c418644f1aafef88d386d071b0d87f7dcf9b9cc641e29048dd
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:        
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false

    hibernate:
      ddl-auto: create-drop